### ISSUE TITLE
Cadastro de Níveis de Instrução

### ISSUE THREAD

**Issue by marciovilasboas** [ojonathacardoso/saap#16]
Os Níveis de Instrução que já estão cadastrados na administração(/admin) não aparecem em Adicionar Contatos, sendo necessário cadastrar novamente pelas Tabelas Auxiliares.

**Comment by ojonathacardoso** [comment]
Após testes, verificamos que no processo de instalação, a importação dos dados ocorria na tabela errada. Corrigimos isto na versão  [v1.3.4](https://github.com/ojonathacardoso/saap/releases/tag/v1.3.4)
